### ISSUE TITLE
Add pivotable reporting

### ISSUE THREAD

**Issue by rnudb** [enioka-Haute-Couture/pyoupyou#301]

**Comment by abessette** [comment]
Based on what has been presented at the last enioka's seminar, we would need :
* Stacked bar chart - x: year-month ; y: process state by firm entity (subsidiary)
* Stacked bar chart - x: firm entity (subsidiary) ; y : source
* Bar chart - x: years and firm entity (subsidiary) ; y: number of candidates from hiring firms
* Bar chart - x: years and firm entity (subsidiary) ; y: percentage of of candidates from hiring firms
* Table chart - x: process state (with total and recruitment percentage) ; y: year with hiring firms or other

**Comment by abessette** [comment]
Data to be removed : 
* Candidate name
* Process state (keep only the process label)
* Interview state -> change to "interview state label"

Set start date of the year in settings file.
Group data by years using the above start date.
